# Node.js CI workflow

# react runs unique tests if the CI environment variable is set
# build: base href is set in package.json at homepage

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn run test
    - name: Build
      run: yarn run build
    - name: Push to gh-pages
      if: github.ref == 'refs/heads/master'
      run: |
         chmod +x ./resources/scripts/update-gh-pages_github.sh
         ./resources/scripts/update-gh-pages_github.sh
